package config

import (
	"fmt"
	"os"
	"time"

	"github.com/giulianozor/filex/internal/atomicfile"
)

// SampleBytes returns the text of a ready-to-edit example config.
//
// When auth is true the example documents multi-user mode (one login-required
// user jail with a note that the password lives in the preferences file);
// otherwise it documents the single shared namespace (no-auth) mode. The return
// value is a []byte so the resulting file is written verbatim, comments and
// all, without passing through a Config round-trip that would strip them.
func SampleBytes(auth bool) []byte {
	if auth {
		return []byte(authSample)
	}
	return []byte(noAuthSample)
}

// WriteSample writes a sample config to path. When a file already exists at
// path it is copied to a timestamped ".bak" sibling first so a regeneration
// never destroys a deployed config. Returns the backup path (empty when there
// was nothing to back up) and the write error.
func WriteSample(path string, auth bool) (string, error) {
	backup, err := backupSample(path)
	if err != nil {
		return "", err
	}
	// Atomic temp+rename so a crash mid-write cannot leave a half-written
	// sample config where the user expects a complete one.
	if err := atomicfile.Write(path, SampleBytes(auth), 0o644); err != nil {
		return backup, err
	}
	return backup, nil
}

// backupSample copies an existing file at path to "<path>.bak.<unix-nano>" so
// generating a sample config never silently replaces the current one. Returns
// "" when path does not exist (nothing to back up).
func backupSample(path string) (string, error) {
	info, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	if info.IsDir() {
		return "", &os.PathError{Op: "backup", Path: path, Err: os.ErrInvalid}
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	backup := path + ".bak." + fmt.Sprint(time.Now().UnixNano())
	if err := os.WriteFile(backup, data, info.Mode().Perm()); err != nil {
		return "", err
	}
	return backup, nil
}

const noAuthSample = `# filex sample configuration - no-auth mode (no login required).
# Generated by: filex -sample-config
#
# Start the server with:
#   ./bin/filex -config config.sample.yaml

host: "0.0.0.0"
port: 8080

# Base path served when no users are configured.
base_path: "/data"

# Show files and directories beginning with a dot.
show_dotfiles: false

# Session lifetime in days (default: 30).
session_ttl_days: 30

# Paths that can never be deleted, renamed or moved (no-auth mode only;
# per-user protection is stored in each user's own ~/.config/filex.yaml).
protected_paths:
  - "/important"
  - "/important/keep.txt"

# Sidebar bookmarks (no-auth mode only; per-user favourites are stored in
# each user's own ~/.config/filex.yaml).
favourites:
  - name: "Home"
    path: "/"

# Parallel ffmpeg processes for thumbnail generation (0 = auto).
thumbnail_parallelism: 0
# Threads per ffmpeg process (0 = single-threaded decode).
thumbnail_threads: 0
# "auto" (use qsv when available), "qsv", or "off".
thumbnail_hardware_accel: "auto"
`

const authSample = `# filex sample configuration - multi-user mode (login required).
# Generated by: filex -sample-config-auth
#
# Start the server with:
#   ./bin/filex -config config.sample.yaml
#
# Each user's DIRECTORY settings live here (base_path jail, uid/gid). Their
# preferences - password hash, show_dotfiles, favourites, protected paths and
# remembered secure-delete settings - are stored in each user's own
# ~/.config/filex.yaml (resolved from the account database, never the home of
# the root daemon) instead, so this file can be read-only and root-managed.
# That file is written 0600 and chowned to each user's uid/gid (config values
# win, account database otherwise) so it is never left root-owned.
#
# Set a sample user's password before anyone can log in (writes the hash into
# the user's own ~/.config/filex.yaml):
#   bin/filex-passwd -user alice

host: "0.0.0.0"
port: 8080
show_dotfiles: false
session_ttl_days: 30

# Each user gets their own path jail and optional uid/gid.
users:
  - username: "alice"
    base_path: "/data/alice"
    # uid: 1001    # omit to skip chown
    # gid: 1001

# Parallel ffmpeg processes for thumbnail generation (0 = auto).
thumbnail_parallelism: 0
# Threads per ffmpeg process (0 = single-threaded decode).
thumbnail_threads: 0
# "auto" (use qsv when available), "qsv", or "off".
thumbnail_hardware_accel: "auto"
`
