// Command gen-openapi regenerates api/openapi.yaml from the route catalog in
// internal/handler. Every registered API endpoint (path, method, auth mode) is
// introspected via handler.APIRoutes, so the shipped OpenAPI document cannot
// drift from the routes actually served. Run it with `make openapi`; the
// pre-commit gate (`make check`) verifies the committed file is up to date.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/giulianozor/filex/internal/atomicfile"
	"github.com/giulianozor/filex/internal/handler"
	"gopkg.in/yaml.v3"
)

func main() {
	out := flag.String("out", filepath.Join("api", "openapi.yaml"), "output file (- for stdout)")
	flag.Parse()

	routes := handler.APIRoutes()
	if len(routes) == 0 {
		fail("no API routes reported by handler.APIRoutes")
	}

	doc := buildDocument(routes)

	var buf bytes.Buffer
	buf.WriteString("# Code generated by tools/gen-openapi. DO NOT EDIT.\n")
	buf.WriteString("# Regenerate with: make openapi\n\n")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(doc); err != nil {
		fail("encode OpenAPI document: %v", err)
	}
	if err := enc.Close(); err != nil {
		fail("close encoder: %v", err)
	}

	if *out == "-" {
		if _, err := os.Stdout.Write(buf.Bytes()); err != nil {
			fail("write stdout: %v", err)
		}
		return
	}
	// Atomic temp+rename so an interrupted run never leaves a truncated spec
	// that `make check` would then compare against.
	if err := atomicfile.Write(*out, buf.Bytes(), 0o644); err != nil {
		fail("write %s: %v", *out, err)
	}
	fmt.Printf("wrote %s (%d paths)\n", *out, len(doc.Paths))
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-openapi: "+format+"\n", args...)
	os.Exit(1)
}

// ---- document shape ---------------------------------------------------------

type document struct {
	OpenAPI    string                `yaml:"openapi"`
	Info       info                  `yaml:"info"`
	Servers    []server              `yaml:"servers"`
	Tags       []tag                 `yaml:"tags"`
	TagGroups  []tagGroup            `yaml:"x-tagGroups"`
	Security   []map[string][]string `yaml:"security"`
	Paths      map[string]pathItem   `yaml:"paths"`
	Components components            `yaml:"components"`
}

type info struct {
	Title       string `yaml:"title"`
	Description string `yaml:"description"`
	Version     string `yaml:"version"`
}

type server struct {
	URL         string `yaml:"url"`
	Description string `yaml:"description,omitempty"`
}

type tag struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description,omitempty"`
}

type tagGroup struct {
	Name string   `yaml:"name"`
	Tags []string `yaml:"tags"`
}

type pathItem map[string]operation

type operation struct {
	Tags        []string       `yaml:"tags,omitempty"`
	Summary     string         `yaml:"summary,omitempty"`
	Description string         `yaml:"description,omitempty"`
	OperationID string         `yaml:"operationId,omitempty"`
	Security    any            `yaml:"security,omitempty"`
	Parameters  []any          `yaml:"parameters,omitempty"`
	RequestBody *requestBody   `yaml:"requestBody,omitempty"`
	Responses   map[string]any `yaml:"responses"`
}

type requestBody struct {
	Required bool           `yaml:"required,omitempty"`
	Content  map[string]any `yaml:"content"`
}

type response struct {
	Description string         `yaml:"description"`
	Content     map[string]any `yaml:"content,omitempty"`
}

type components struct {
	SecuritySchemes map[string]any `yaml:"securitySchemes"`
	Parameters      map[string]any `yaml:"parameters"`
	Responses       map[string]any `yaml:"responses"`
	Schemas         map[string]any `yaml:"schemas"`
}

// ---- builders ---------------------------------------------------------------

func schemaRef(name string) map[string]any {
	return map[string]any{"$ref": "#/components/schemas/" + name}
}

func paramRef(name string) map[string]any {
	return map[string]any{"$ref": "#/components/parameters/" + name}
}

func respRef(name string) map[string]any {
	return map[string]any{"$ref": "#/components/responses/" + name}
}

// jsonContent wraps a schema as an application/json media type.
func jsonContent(schema any) map[string]any {
	return map[string]any{"application/json": map[string]any{"schema": schema}}
}

// binaryContent wraps a binary payload as the given media type.
func binaryContent(mediaType string) map[string]any {
	return map[string]any{mediaType: map[string]any{
		"schema": map[string]any{"type": "string", "format": "binary"},
	}}
}

// withErrorResponses adds $ref error responses to a success response map.
func withErrorResponses(base map[string]any, names ...string) map[string]any {
	for _, name := range names {
		base[errorStatus(name)] = respRef(name)
	}
	return base
}

func errorStatus(name string) string {
	switch name {
	case "BadRequest":
		return "400"
	case "Unauthorized":
		return "401"
	case "Forbidden":
		return "403"
	case "NotFound":
		return "404"
	case "Conflict":
		return "409"
	case "ServerError":
		return "500"
	}
	// Fail loudly rather than silently emitting a catch-all "default" key that
	// hides a typo in a withErrorResponses call.
	fail("unknown error response name %q", name)
	return ""
}

func okJSON() map[string]any {
	return map[string]any{"200": response{Description: "Success", Content: jsonContent(schemaRef("OK"))}}
}

func buildDocument(routes []handler.APIRoute) document {
	paths := make(map[string]pathItem, len(routes))
	for _, r := range routes {
		item, ok := paths[r.Pattern]
		if !ok {
			item = pathItem{}
			paths[r.Pattern] = item
		}
		item[methodKey(r.Method)] = operationFor(r)
	}
	return document{
		OpenAPI: "3.0.3",
		Info: info{
			Title: "filex API",
			Description: "HTTP API of filex, a self-hosted web-based file browser. All endpoints live " +
				"under `/api/`. When authentication is enabled (any `users:` entry in `config.yaml`) every " +
				"endpoint except `/api/login` and `/api/version` requires a valid `filex_session` cookie set " +
				"by `/api/login`; in no-auth mode the same endpoints work without one.",
			Version: "1.0",
		},
		Servers: []server{{
			URL:         "/",
			Description: "The base URL that hosts filex (all documented paths include the /api prefix)",
		}},
		Tags: []tag{
			{Name: "auth", Description: "Session login, logout and identity"},
			{Name: "files", Description: "Directory listing and file operations"},
			{Name: "favourites", Description: "Sidebar bookmark management"},
			{Name: "protected", Description: "Delete-protection paths"},
			{Name: "config", Description: "Server configuration"},
			{Name: "video", Description: "Video thumbnails, keyframe snapping and clip extraction"},
			{Name: "archives", Description: "Archive inspection and extraction"},
		},
		TagGroups: []tagGroup{
			{Name: "Auth", Tags: []string{"auth"}},
			{Name: "Files", Tags: []string{"files"}},
			{Name: "Favourites", Tags: []string{"favourites"}},
			{Name: "Protected paths", Tags: []string{"protected"}},
			{Name: "Configuration", Tags: []string{"config"}},
			{Name: "Video editing", Tags: []string{"video"}},
			{Name: "Archives", Tags: []string{"archives"}},
		},
		Security:   []map[string][]string{{"cookieAuth": {}}},
		Paths:      paths,
		Components: buildComponents(),
	}
}

func methodKey(method string) string {
	switch method {
	case "GET":
		return "get"
	case "POST":
		return "post"
	case "PUT":
		return "put"
	case "DELETE":
		return "delete"
	case "PATCH":
		return "patch"
	}
	fail("unsupported HTTP method %q in route catalog", method)
	return ""
}

// ---- component schemas ------------------------------------------------------

func buildComponents() components {
	return components{
		SecuritySchemes: map[string]any{
			"cookieAuth": map[string]any{
				"type":        "apiKey",
				"in":          "cookie",
				"name":        "filex_session",
				"description": "Session token set by /api/login",
			},
		},
		Parameters: map[string]any{
			"Path": map[string]any{
				"name":        "path",
				"in":          "query",
				"description": `Virtual path inside the jail (default "/")`,
				"schema":      map[string]any{"type": "string"},
			},
			"Id": map[string]any{
				"name":        "id",
				"in":          "query",
				"required":    true,
				"description": "1-based thumbnail frame number",
				"schema":      map[string]any{"type": "integer", "minimum": 1},
			},
		},
		Responses: map[string]any{
			"OK":           response{Description: "Success", Content: jsonContent(schemaRef("OK"))},
			"BadRequest":   errorResponse("Invalid or rejected request"),
			"Unauthorized": errorResponse("Missing or invalid credentials/session"),
			"Forbidden":    errorResponse("Resource exists but access is denied"),
			"NotFound":     errorResponse("Resource not found"),
			"Conflict":     errorResponse("Conflict with concurrent state"),
			"ServerError":  errorResponse("Internal server error"),
		},
		Schemas: buildSchemas(),
	}
}

func errorResponse(desc string) response {
	return response{Description: desc, Content: jsonContent(schemaRef("Error"))}
}

// obj builds an object schema. required may be nil.
func obj(required []string, props map[string]any) map[string]any {
	m := map[string]any{"type": "object", "properties": props}
	if len(required) > 0 {
		m["required"] = required
	}
	return m
}

func str() map[string]any { return map[string]any{"type": "string"} }
func strFmt(f string) map[string]any {
	return map[string]any{"type": "string", "format": f}
}
func intT() map[string]any   { return map[string]any{"type": "integer"} }
func int64T() map[string]any { return map[string]any{"type": "integer", "format": "int64"} }
func numT() map[string]any   { return map[string]any{"type": "number"} }
func boolT() map[string]any  { return map[string]any{"type": "boolean"} }

func arr(items any) map[string]any { return map[string]any{"type": "array", "items": items} }

func buildSchemas() map[string]any {
	schemas := map[string]any{
		"OK": obj([]string{"status"}, map[string]any{
			"status": map[string]any{"type": "string", "enum": []string{"ok"}},
		}),
		"Error": obj([]string{"error"}, map[string]any{
			"error": str(),
		}),
		"LoginRequest": obj([]string{"username", "password"}, map[string]any{
			"username":    str(),
			"password":    strFmt("password"),
			"remember_me": map[string]any{"type": "boolean", "default": false},
		}),
		"LoginResponse": obj([]string{"status", "username"}, map[string]any{
			"status":   map[string]any{"type": "string", "enum": []string{"ok"}},
			"username": str(),
		}),
		"MeResponse": obj([]string{"username", "auth_required"}, map[string]any{
			"username":      str(),
			"auth_required": boolT(),
		}),
		"ChangePasswordRequest": obj([]string{"current_password", "new_password"}, map[string]any{
			"current_password": strFmt("password"),
			"new_password":     strFmt("password"),
		}),
		"FileEntry": obj([]string{"name", "path", "size", "mod_time", "is_dir", "mode", "mime_hint"}, map[string]any{
			"name":      str(),
			"path":      str(),
			"size":      int64T(),
			"mod_time":  strFmt("date-time"),
			"is_dir":    boolT(),
			"mode":      map[string]any{"type": "integer", "format": "int64", "description": "os.FileMode bitmask"},
			"mime_hint": str(),
		}),
		"FileEntryList": arr(schemaRef("FileEntry")),
		"DiskUsage": obj([]string{"total", "free", "used", "used_pct"}, map[string]any{
			"total":    int64T(),
			"free":     int64T(),
			"used":     int64T(),
			"used_pct": numT(),
		}),
		"InfoResponse": obj([]string{"file", "disk", "disk_error"}, map[string]any{
			"file": schemaRef("FileEntry"),
			"disk": schemaRef("DiskUsage"),
			"disk_error": map[string]any{
				"type":        "string",
				"nullable":    true,
				"description": "Present when statfs failed (disk may be null)",
			},
		}),
		"CreateFileResponse": obj([]string{"status", "path"}, map[string]any{
			"status": str(),
			"path":   str(),
		}),
		"ReadResponse": obj([]string{"content"}, map[string]any{
			"content": str(),
		}),
		"WriteRequest": obj([]string{"path", "content"}, map[string]any{
			"path":    str(),
			"content": str(),
		}),
		"ZipRequest": obj([]string{"paths"}, map[string]any{
			"paths": arr(str()),
		}),
		"FolderInfoResponse": obj([]string{"name", "path", "total_size", "file_count"}, map[string]any{
			"name":       str(),
			"path":       str(),
			"mod_time":   strFmt("date-time"),
			"total_size": int64T(),
			"file_count": int64T(),
		}),
		"Favourite": obj([]string{"name", "path"}, map[string]any{
			"name": str(),
			"path": str(),
		}),
		"FavouriteAddRequest": obj([]string{"path"}, map[string]any{
			"path": str(),
			"name": map[string]any{"type": "string", "maxLength": 64},
		}),
		"FavouritesUpdateRequest": obj([]string{"favourites"}, map[string]any{
			"favourites": map[string]any{"type": "array", "maxItems": 100, "items": schemaRef("Favourite")},
		}),
		"NameRequest": obj([]string{"path", "name"}, map[string]any{
			"path": str(),
			"name": map[string]any{"type": "string", "description": "Single entry name, no path separators"},
		}),
		"RenameRequest": obj([]string{"path", "newname"}, map[string]any{
			"path":    str(),
			"newname": str(),
		}),
		"PathRequest": obj([]string{"path"}, map[string]any{
			"path": str(),
		}),
		"DeleteRequest": obj([]string{"path"}, map[string]any{
			"path":  map[string]any{"type": "string", "description": "Single target (alternative to paths)"},
			"paths": arr(str()),
			"wipe":  map[string]any{"type": "boolean", "default": false},
			"method": map[string]any{
				"type":        "string",
				"description": "Secure-delete algorithm id (see /api/config wipe_methods)",
				"default":     "fast",
			},
		}),
		"MoveCopyRequest": obj([]string{"dst"}, map[string]any{
			"src":  map[string]any{"type": "string", "description": "Single source (alternative to srcs)"},
			"srcs": arr(str()),
			"dst":  str(),
			"on_conflict": map[string]any{
				"type":    "string",
				"enum":    []string{"error", "overwrite", "rename"},
				"default": "error",
			},
		}),
		"WipeMethod": obj([]string{"id", "name", "description"}, map[string]any{
			"id":          str(),
			"name":        str(),
			"description": str(),
		}),
		"DeletePrefs": obj(nil, map[string]any{
			"default_wipe": map[string]any{"type": "boolean", "default": false, "description": "Remember to enable secure wipe in the delete dialog"},
			"wipe_method":  map[string]any{"type": "string", "default": "fast", "description": "Remembered secure-delete algorithm id (see /api/config wipe_methods)"},
		}),
		"ShowDotfilesRequest": obj([]string{"show_dotfiles"}, map[string]any{
			"show_dotfiles": boolT(),
		}),
		"Config": obj(
			[]string{"host", "port", "show_dotfiles", "auth_required", "session_ttl_days", "wipe_methods",
				"ffmpeg_available", "ffprobe_available", "unzip_available", "sevenzip_available", "unrar_available", "tar_available"},
			map[string]any{
				"host":               str(),
				"port":               intT(),
				"show_dotfiles":      boolT(),
				"auth_required":      boolT(),
				"session_ttl_days":   intT(),
				"wipe_methods":       arr(schemaRef("WipeMethod")),
				"ffmpeg_available":   boolT(),
				"ffprobe_available":  boolT(),
				"unzip_available":    boolT(),
				"sevenzip_available": boolT(),
				"unrar_available":    boolT(),
				"tar_available":      boolT(),
			}),
		"ThumbnailEntry": obj([]string{"name", "time", "index"}, map[string]any{
			"name":  map[string]any{"type": "string", "description": `On-disk frame filename, e.g. "00001.jpg"`},
			"time":  map[string]any{"type": "number", "description": "Keyframe PTS in seconds"},
			"index": map[string]any{"type": "integer", "description": "1-based frame number"},
		}),
		"ThumbnailsResponse": obj([]string{"thumbnails", "generating"}, map[string]any{
			"thumbnails": arr(schemaRef("ThumbnailEntry")),
			"generating": boolT(),
			"waiting":    boolT(),
			"total":      map[string]any{"type": "integer", "description": "Estimated thumbnail count while generating"},
			"completed":  map[string]any{"type": "integer", "description": "Frames written so far while generating"},
			"error":      map[string]any{"type": "string", "description": "Generation failure when not generating"},
		}),
		"TimeSpan": obj([]string{"start", "end"}, map[string]any{
			"start": map[string]any{"type": "number", "description": "Start seconds (>= 0)"},
			"end":   map[string]any{"type": "number", "description": "End seconds, finite and strictly after start"},
		}),
		"VideoExtractRequest": obj([]string{"path", "segments"}, map[string]any{
			"path":     str(),
			"segments": map[string]any{"type": "array", "maxItems": 32, "items": schemaRef("TimeSpan")},
		}),
		"VideoSaveIntervalsRequest": obj([]string{"path", "intervals"}, map[string]any{
			"path":      str(),
			"intervals": arr(schemaRef("TimeSpan")),
		}),
		"IntervalsResponse": obj([]string{"intervals"}, map[string]any{
			"intervals": arr(schemaRef("TimeSpan")),
		}),
		"SnapTimeRequest": obj([]string{"path", "time"}, map[string]any{
			"path": str(),
			"time": map[string]any{"type": "number", "minimum": 0},
		}),
		"SnapTimeResponse": obj([]string{"prev", "next"}, map[string]any{
			"prev": numT(),
			"next": numT(),
		}),
		"BatchStatusResponse": obj([]string{"active", "paths"}, map[string]any{
			"active": boolT(),
			"paths":  arr(str()),
		}),
		"BatchThumbnailsRequest": obj([]string{"paths"}, map[string]any{
			"paths": arr(str()),
		}),
		"BatchThumbnailsResponse": obj([]string{"status", "paths", "skipped", "total"}, map[string]any{
			"status": map[string]any{"type": "string", "example": "started"},
			"paths":  arr(str()),
			"skipped": map[string]any{
				"type":                 "object",
				"additionalProperties": str(),
			},
			"total": intT(),
		}),
		"ExtractArchiveRequest": obj([]string{"path"}, map[string]any{
			"path":     str(),
			"password": map[string]any{"type": "string", "description": "Archive password for encrypted archives"},
		}),
		"NDJSONProgress": obj([]string{"type"}, map[string]any{
			"type":     map[string]any{"type": "string", "enum": []string{"progress"}},
			"done":     map[string]any{"type": "integer", "description": "Files processed so far (transfer streams)"},
			"total":    map[string]any{"type": "integer", "description": "Total files in the operation"},
			"current":  map[string]any{"type": "string", "description": "Basename of the file currently being processed"},
			"filePct":  map[string]any{"type": "number", "nullable": true, "description": "Fraction of the current file completed (0-1), when measurable"},
			"segment":  map[string]any{"type": "integer", "description": "1-based segment index (video extract)"},
			"command":  map[string]any{"type": "string", "description": "ffmpeg command run (video extract)"},
			"status":   map[string]any{"type": "string", "description": `Special progress status, e.g. "concatenating"`},
			"line":     map[string]any{"type": "string", "description": "Raw extraction tool output line (archive extract)"},
			"filename": map[string]any{"type": "string", "description": "Archive basename being extracted"},
			"tool":     map[string]any{"type": "string", "description": "Extraction tool name"},
		}),
		"NDJSONResult": obj([]string{"type", "status"}, map[string]any{
			"type":   map[string]any{"type": "string", "enum": []string{"result"}},
			"status": map[string]any{"type": "string", "enum": []string{"ok"}},
			"output": map[string]any{"type": "string", "description": "Virtual path of the produced file (video extract)"},
			"dest":   map[string]any{"type": "string", "description": "Virtual path of the extraction destination (archive extract)"},
			"tool":   str(),
		}),
		"NDJSONError": obj([]string{"type", "message"}, map[string]any{
			"type":    map[string]any{"type": "string", "enum": []string{"error"}},
			"message": str(),
			"code":    map[string]any{"type": "string", "description": `Machine-readable code, e.g. "destination_exists"`},
			"conflicts": map[string]any{
				"type":        "array",
				"items":       str(),
				"description": "Conflicting destination paths with code destination_exists",
			},
			"tool": str(),
		}),
		"NDJSONEvent": map[string]any{
			"oneOf": []any{
				schemaRef("NDJSONProgress"),
				schemaRef("NDJSONResult"),
				schemaRef("NDJSONError"),
			},
		},
		"NDJSONStream": map[string]any{
			"type":        "object",
			"description": "One NDJSON event per line (Content-Type application/x-ndjson)",
			"properties": map[string]any{
				"events": arr(schemaRef("NDJSONEvent")),
			},
		},
	}
	return schemas
}

// ---- per-endpoint operations ------------------------------------------------

func operationFor(r handler.APIRoute) operation {
	op := operation{
		OperationID: r.Handler,
		Responses:   map[string]any{},
	}
	if r.Public {
		// Explicit [] overrides the global cookieAuth requirement.
		op.Security = []map[string][]string{}
	}

	switch r.Handler {
	case "handleLogin":
		op.Tags = []string{"auth"}
		op.Summary = "Log in and establish a session"
		op.Description = "Returns ok immediately (with the \"anonymous\" username) when auth is disabled. " +
			"Otherwise validates the credentials and sets the `filex_session` cookie. A `remember_me: true` " +
			"login issues a persistent cookie with the full session TTL; a plain login issues a session " +
			"cookie discarded when the browser closes."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("LoginRequest"))}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "Login succeeded (or auth is disabled)", Content: jsonContent(schemaRef("LoginResponse"))},
		}, "BadRequest", "Unauthorized")

	case "handleVersion":
		op.Tags = []string{"auth"}
		op.Summary = "Report the server version"
		op.Description = "Public endpoint used by the Docker HEALTHCHECK."
		op.Responses = map[string]any{
			"200": response{Description: "Version string", Content: jsonContent(obj([]string{"version"}, map[string]any{
				"version": map[string]any{"type": "string", "example": "1.2.3"},
			}))},
		}

	case "handleLogout":
		op.Tags = []string{"auth"}
		op.Summary = "Log out and clear the session cookie"
		op.Responses = okJSON()

	case "handleMe":
		op.Tags = []string{"auth"}
		op.Summary = "Report the authenticated identity"
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "Identity (anonymous when auth is disabled)", Content: jsonContent(schemaRef("MeResponse"))},
		}, "Unauthorized")

	case "handleChangePassword":
		op.Tags = []string{"auth"}
		op.Summary = "Change the authenticated user's login password"
		op.Description = "Requires `current_password` and replaces the stored bcrypt hash in " +
			"`~/.config/filex.yaml` with a hash of `new_password` (at most 72 bytes). The current session " +
			"(and any other sessions for this user) stays valid."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("ChangePasswordRequest"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest", "Unauthorized")

	case "handleList":
		op.Tags = []string{"files"}
		op.Summary = "List directory contents"
		op.Parameters = []any{paramRef("Path")}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "Directory entries (dotfiles included only when enabled)", Content: jsonContent(schemaRef("FileEntryList"))},
		}, "BadRequest")

	case "handleDownload":
		op.Tags = []string{"files"}
		op.Summary = "Download a file as an attachment"
		op.Parameters = []any{paramRef("Path")}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "File content with Content-Disposition: attachment", Content: binaryContent("application/octet-stream")},
		}, "BadRequest", "NotFound")

	case "handleStream":
		op.Tags = []string{"files"}
		op.Summary = "Stream a media file inline"
		op.Description = "Supports HTTP range requests (seeking) via ServeContent."
		op.Parameters = []any{paramRef("Path")}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "File content for inline playback", Content: binaryContent("application/octet-stream")},
			"206": response{Description: "Partial content in response to a Range request"},
		}, "BadRequest", "NotFound")

	case "handleUpload":
		op.Tags = []string{"files"}
		op.Summary = "Upload files (or one chunk of a file)"
		op.Description = "Multipart form with one or more \"file\" parts. Whole-file uploads write each part " +
			"to `path`. Chunked uploads pass `offset` (byte offset) and `total` (final file size) as query " +
			"parameters and accept exactly one part; the chunk is written at the given offset."
		op.Parameters = []any{
			map[string]any{
				"name": "path", "in": "query", "description": `Destination directory (default "/")`,
				"schema": map[string]any{"type": "string", "default": "/"},
			},
			map[string]any{
				"name": "offset", "in": "query", "description": "Byte offset for chunked upload mode",
				"schema": map[string]any{"type": "integer", "format": "int64", "minimum": 0},
			},
			map[string]any{
				"name": "total", "in": "query", "description": "Declared final size for chunked upload mode",
				"schema": map[string]any{"type": "integer", "format": "int64", "minimum": 1},
			},
		}
		op.RequestBody = &requestBody{Required: true, Content: map[string]any{
			"multipart/form-data": map[string]any{"schema": obj([]string{"file"}, map[string]any{
				"file": arr(map[string]any{"type": "string", "format": "binary"}),
			})},
		}}
		op.Responses = withErrorResponses(okJSON(), "BadRequest", "ServerError")

	case "handleMkdir":
		op.Tags = []string{"files"}
		op.Summary = "Create a directory inside a parent"
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("NameRequest"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest")

	case "handleCreateFile":
		op.Tags = []string{"files"}
		op.Summary = "Create an empty file (fails if it exists)"
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("NameRequest"))}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "Created file's virtual path", Content: jsonContent(schemaRef("CreateFileResponse"))},
		}, "BadRequest")

	case "handleRename":
		op.Tags = []string{"files"}
		op.Summary = "Rename a file or directory"
		op.Description = "Delete protection carries over to the new name."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("RenameRequest"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest")

	case "handleDelete":
		op.Tags = []string{"files"}
		op.Summary = "Delete files (optionally with a secure wipe)"
		op.Description = "Plain deletes remove the target immediately. With `wipe: true` the bytes are " +
			"overwritten first using the chosen `method`, and progress is streamed as NDJSON (one " +
			"standard-progress line per target)."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("DeleteRequest"))}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{
				Description: "Delete acknowledged; for a wipe this is 200 with an application/x-ndjson body ending in a result line.",
				Content:     mergeContent(jsonContent(schemaRef("OK")), ndjsonContent()),
			},
		}, "BadRequest")

	case "handleMove":
		op.Tags = []string{"files"}
		op.Summary = "Move file(s) or directories"
		op.Description = "Progress is streamed as NDJSON."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("MoveCopyRequest"))}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "NDJSON progress stream ending in a result (or an error line with conflicts)", Content: ndjsonContent()},
		}, "BadRequest")

	case "handleCopy":
		op.Tags = []string{"files"}
		op.Summary = "Copy file(s) or directories"
		op.Description = "Progress is streamed as NDJSON (same shape as move)."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("MoveCopyRequest"))}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "NDJSON progress stream ending in a result (or an error line with conflicts)", Content: ndjsonContent()},
		}, "BadRequest")

	case "handleZipDownload":
		op.Tags = []string{"files"}
		op.Summary = "Download selected paths as a ZIP archive"
		op.Description = "All paths are verified to exist before streaming begins."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("ZipRequest"))}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "ZIP archive", Content: binaryContent("application/zip")},
		}, "BadRequest", "NotFound")

	case "handleRead":
		op.Tags = []string{"files"}
		op.Summary = "Read a text file"
		op.Parameters = []any{paramRef("Path")}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "File content", Content: jsonContent(schemaRef("ReadResponse"))},
		}, "BadRequest")

	case "handleWrite":
		op.Tags = []string{"files"}
		op.Summary = "Write a text file (atomic save)"
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("WriteRequest"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest")

	case "handleInfo":
		op.Tags = []string{"files"}
		op.Summary = "File metadata and disk usage"
		op.Parameters = []any{paramRef("Path")}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "File entry plus disk statistics", Content: jsonContent(schemaRef("InfoResponse"))},
		}, "Forbidden", "NotFound")

	case "handleFolderInfo":
		op.Tags = []string{"files"}
		op.Summary = "Folder size and file count"
		op.Parameters = []any{paramRef("Path")}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "Folder statistics", Content: jsonContent(schemaRef("FolderInfoResponse"))},
		}, "BadRequest", "NotFound", "ServerError")

	case "handleFavourites":
		op.Tags = []string{"favourites"}
		op.Summary = "List favourites for the current user"
		op.Responses = map[string]any{
			"200": response{Description: "Favourites (Home first, sorted by name)", Content: jsonContent(arr(schemaRef("Favourite")))},
		}

	case "handleFavouritesAdd":
		op.Tags = []string{"favourites"}
		op.Summary = "Add a favourite (path must be an existing directory)"
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("FavouriteAddRequest"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest")

	case "handleFavouritesRemove":
		op.Tags = []string{"favourites"}
		op.Summary = "Remove a favourite by path"
		op.Description = "Removing a non-existent favourite is a no-op."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("PathRequest"))}
		op.Responses = okJSON()

	case "handleFavouritesUpdate":
		op.Tags = []string{"favourites"}
		op.Summary = "Replace the full favourite list"
		op.Description = "Every submitted path must be an existing directory."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("FavouritesUpdateRequest"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest")

	case "handleProtected":
		op.Tags = []string{"protected"}
		op.Summary = "List delete-protected paths for the current user"
		op.Responses = map[string]any{
			"200": response{Description: "Protected virtual paths", Content: jsonContent(arr(str()))},
		}

	case "handleProtectedAdd":
		op.Tags = []string{"protected"}
		op.Summary = "Protect a path from deletion"
		op.Description = "The path must exist before it can be protected."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("PathRequest"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest")

	case "handleProtectedRemove":
		op.Tags = []string{"protected"}
		op.Summary = "Unprotect a path"
		op.Description = "Removing a path that is not protected is a no-op."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("PathRequest"))}
		op.Responses = okJSON()

	case "handleDeletePrefs":
		op.Tags = []string{"config"}
		op.Summary = "List remembered secure-delete preferences"
		op.Description = "Returns the remembered secure-delete (wipe) toggle and algorithm for the " +
			"current user (the global entry in no-auth mode). Stored in ~/.config/filex.yaml."
		op.Responses = map[string]any{
			"200": response{Description: "Remembered wipe preferences", Content: jsonContent(schemaRef("DeletePrefs"))},
		}

	case "handleDeletePrefsUpdate":
		op.Tags = []string{"config"}
		op.Summary = "Persist remembered secure-delete preferences"
		op.Description = "Stores the remembered `default_wipe` toggle and `wipe_method` for the current " +
			"user in ~/.config/filex.yaml. `wipe_method` must be one of the ids reported by /api/config."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("DeletePrefs"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest")

	case "handleConfig":
		op.Tags = []string{"config"}
		op.Summary = "Safe server configuration"
		op.Description = "No secrets are exposed; tool availability drives UI affordances."
		op.Responses = map[string]any{
			"200": response{Description: "Server configuration", Content: jsonContent(schemaRef("Config"))},
		}

	case "handleShowDotfiles":
		op.Tags = []string{"config"}
		op.Summary = "Persist the show-dotfiles preference"
		op.Description = "Stores the sidebar dotfiles toggle for the current user in " +
			"~/.config/filex.yaml (or updates the config.yaml server default in no-auth mode)."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("ShowDotfilesRequest"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest")

	case "handleVideoThumbnails":
		op.Tags = []string{"video"}
		op.Summary = "List (and lazily generate) a video's thumbnails"
		op.Description = "Returns cached thumbnails. When none are cached and generation is not already " +
			"running it is started in the background and `generating: true` (plus total/completed estimates) " +
			"is returned; `waiting: true` marks a video queued in a batch."
		op.Parameters = []any{paramRef("Path")}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "Thumbnail manifest (possibly with generation status)", Content: jsonContent(schemaRef("ThumbnailsResponse"))},
		}, "BadRequest", "ServerError")

	case "handleVideoThumbnailImage":
		op.Tags = []string{"video"}
		op.Summary = "Serve one thumbnail image"
		op.Parameters = []any{paramRef("Path"), paramRef("Id")}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "JPEG thumbnail", Content: binaryContent("image/jpeg")},
		}, "BadRequest", "NotFound")

	case "handleVideoExtract":
		op.Tags = []string{"video"}
		op.Summary = "Extract video segments and concatenate them (stream copy)"
		op.Description = "Progress is streamed as NDJSON; the final result carries the output path."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("VideoExtractRequest"))}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "NDJSON progress stream ending in a result with the output path", Content: ndjsonContent()},
		}, "BadRequest")

	case "handleVideoDeleteThumbnails":
		op.Tags = []string{"video"}
		op.Summary = "Delete a video's thumbnail cache and saved intervals"
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("PathRequest"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest", "Conflict")

	case "handleVideoCancelThumbnails":
		op.Tags = []string{"video"}
		op.Summary = "Cancel thumbnails generation for a video"
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("PathRequest"))}
		op.Responses = okJSON()

	case "handleVideoSaveIntervals":
		op.Tags = []string{"video"}
		op.Summary = "Persist clip interval definitions for a video"
		op.Description = "An empty `intervals` array deletes the saved intervals file."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("VideoSaveIntervalsRequest"))}
		op.Responses = withErrorResponses(okJSON(), "BadRequest")

	case "handleVideoLoadIntervals":
		op.Tags = []string{"video"}
		op.Summary = "Load saved clip intervals for a video"
		op.Description = "Returns an empty list when nothing is saved yet."
		op.Parameters = []any{paramRef("Path")}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "Saved intervals", Content: jsonContent(schemaRef("IntervalsResponse"))},
		}, "BadRequest")

	case "handleVideoSnapTime":
		op.Tags = []string{"video"}
		op.Summary = "Snap a time to the nearest keyframes"
		op.Description = "Returns the previous and next keyframe times around `time`."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("SnapTimeRequest"))}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "Snapped keyframe boundaries", Content: jsonContent(schemaRef("SnapTimeResponse"))},
		}, "BadRequest")

	case "handleVideoBatchStatus":
		op.Tags = []string{"video"}
		op.Summary = "Report the active thumbnail batch for the current user"
		op.Responses = map[string]any{
			"200": response{Description: "Batch status and pending paths", Content: jsonContent(schemaRef("BatchStatusResponse"))},
		}

	case "handleVideoBatchThumbnails":
		op.Tags = []string{"video"}
		op.Summary = "Queue thumbnail generation for many videos"
		op.Description = "Returns immediately; progress is polled per-video via /api/video-thumbnails."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("BatchThumbnailsRequest"))}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "Batch queued", Content: jsonContent(schemaRef("BatchThumbnailsResponse"))},
		}, "BadRequest")

	case "handleExtractArchive":
		op.Tags = []string{"archives"}
		op.Summary = "Extract an archive into a directory next to it"
		op.Description = "Streams the extraction tool's output as NDJSON. The tool is chosen from the " +
			"archive extension (unzip/unrar/tar/7z), preferring a dedicated tool and falling back to 7z."
		op.RequestBody = &requestBody{Required: true, Content: jsonContent(schemaRef("ExtractArchiveRequest"))}
		op.Responses = withErrorResponses(map[string]any{
			"200": response{Description: "NDJSON progress stream ending in a result with the destination", Content: ndjsonContent()},
		}, "BadRequest", "NotFound")
	}

	return op
}

func ndjsonContent() map[string]any {
	return map[string]any{"application/x-ndjson": map[string]any{"schema": schemaRef("NDJSONStream")}}
}

func mergeContent(a, b map[string]any) map[string]any {
	for k, v := range b {
		a[k] = v
	}
	return a
}
